COLOR_DICT = {
  'hwang_dd': (130, 130, 0),
  'hwang_d': (200, 200, 0),
  'hwang': (230, 230, 0),
  'hwang_u': (255, 255, 90),
  'hwang_uu': (255, 255, 150),

  'joong_dd': (100, 0, 0),
  'joong_d': (200, 0, 0),
  'joong': (255, 0, 0),
  'joong_u': (255, 128, 128),
  'joong_uu': (255, 192, 192),

  'lim_dd': (0, 100, 0), 
  'lim_d': (0, 170, 0), 
  'lim': (0, 230, 0), 
  'lim_u': (100, 255, 100), 
  'lim_uu': (182, 255, 182), 
  
  'mu_dd': (100, 0, 100), 
  'mu_d': (130, 0, 130), 
  'mu': (255, 0, 255), 
  'mu_u': (255, 100, 255), 
  'mu_uu': (255, 182, 255), 
  
  'nam_dd': (0, 0, 150), 
  'nam_d': (0, 0, 200), 
  'nam': (0, 0, 255), 
  'nam_u': (80, 80, 255), 
  'nam_uu': (130, 130, 235), 

  'tae_dd': (110, 60, 0), 
  'tae_d': (200, 132, 0), 
  'tae': (255, 165, 0), 
  'tae_u': (255, 192, 100), 
  'tae_uu': (255, 218, 150), 
}

PNAME_LIST = ['하하배황', '하하배대', '하하배태', '하하배협', '하하배고', '하하배중', '하하배유', '하하배임', '하하배이', '하하배남', '하하배무', '하하배응', '하배황', '하배대', '하배태', '하배협', '하배고', '하배중', '하배유', '하배임', '하배이', '하배남', '하배무', '하배응', '배황', '배대', '배태', '배협', '배고', '배중', '배유', '배임', '배이', '배남', '배무', '배응', '황', '대', '태', '협', '고', '중', '유', '임', '이', '남', '무', '응', '청황', '청대', '청태', '청협', '청고', '청중', '청유', '청임', '청이', '청남', '청무', '청응', '중청황', '중청대', '중청태', '중청협', '중청고', '중청중', '중청유', '중청임', '중청이', '중청남', '중청무', '중청응', '-']
PNAME_EN_LIST = ['hwang_ddd', 'dae_ddd', 'tae_ddd', 'hyeop_ddd', 'go_ddd', 'joong_ddd', 'yu_ddd', 'lim_ddd', 'ee_ddd', 'nam_ddd', 'mu_ddd', 'eung_ddd', 'hwang_dd', 'dae_dd', 'tae_dd', 'hyeop_dd', 'go_dd', 'joong_dd', 'yu_dd', 'lim_dd', 'ee_dd', 'nam_dd', 'mu_dd', 'eung_dd', 'hwang_d', 'dae_d', 'tae_d', 'hyeop_d', 'go_d', 'joong_d', 'yu_d', 'lim_d', 'ee_d', 'nam_d', 'mu_d', 'eung_d', 'hwang', 'dae', 'tae', 'hyeop', 'go', 'joong', 'yu', 'lim', 'ee', 'nam', 'mu', 'eung', 'hwang_u', 'dae_u', 'tae_u', 'hyeop_u', 'go_u', 'joong_u', 'yu_u', 'lim_u', 'ee_u', 'nam_u', 'mu_u', 'eung_u', 'hwang_uu', 'dae_uu', 'tae_uu', 'hyeop_uu', 'go_uu', 'joong_uu', 'yu_uu', 'lim_uu', 'ee_uu', 'nam_uu', 'mu_uu', 'eung_uu', 'conti', 'pause']

SPECIAL_CHAR_TO_NAME = {
  '^': "니레",
  'ㄷ': "나니로",
  '(': "추성",
  ')': "퇴성",
}

PNAME_EN_TO_KR = {
  'hwang_ddd': '하하배황',
  'dae_ddd': '하하배대',
  'tae_ddd': '하하배태',
  'hyeop_ddd': '하하배협',
  'go_ddd': '하하배고',
  'joong_ddd': '하하배중',
  'yu_ddd': '하하배유',
  'lim_ddd': '하하배임',
  'ee_ddd': '하하배이',
  'nam_ddd': '하하배남',
  'mu_ddd': '하하배무',
  'eung_ddd': '하하배응',
  'hwang_dd': '하배황',
  'dae_dd': '하배대',
  'tae_dd': '하배태',
  'hyeop_dd': '하배협',
  'go_dd': '하배고',
  'joong_dd': '하배중',
  'yu_dd': '하배유',
  'lim_dd': '하배임',
  'ee_dd': '하배이',
  'nam_dd': '하배남',
  'mu_dd': '하배무',
  'eung_dd': '하배응',
  'hwang_d': '배황',
  'dae_d': '배대',
  'tae_d': '배태',
  'hyeop_d': '배협',
  'go_d': '배고',
  'joong_d': '배중',
  'yu_d': '배유',
  'lim_d': '배임',
  'ee_d': '배이',
  'nam_d': '배남',
  'mu_d': '배무',
  'eung_d': '배응',
  'hwang': '황',
  'dae': '대',
  'tae': '태',
  'hyeop': '협',
  'go': '고',
  'joong': '중',
  'yu': '유',
  'lim': '임',
  'ee': '이',
  'nam': '남',
  'mu': '무',
  'eung': '응',
  'hwang_u': '청황',
  'dae_u': '청대',
  'tae_u': '청태',
  'hyeop_u': '청협',
  'go_u': '청고',
  'joong_u': '청중',
  'yu_u': '청유',
  'lim_u': '청임',
  'ee_u': '청이',
  'nam_u': '청남',
  'mu_u': '청무',
  'eung_u': '청응',
  'hwang_uu': '중청황',
  'dae_uu': '중청대',
  'tae_uu': '중청태',
  'hyeop_uu': '중청협',
  'go_uu': '중청고',
  'joong_uu': '중청중',
  'yu_uu': '중청유',
  'lim_uu': '중청임',
  'ee_uu': '중청이',
  'nam_uu': '중청남',
  'mu_uu': '중청무',
  'eung_uu': '중청응',
  'conti': '-',
  'pause': '쉼표',
}

PNAME_KR_TO_EN = {
  '하하배황': 'hwang_ddd',
  '하하배대': 'dae_ddd',
  '하하배태': 'tae_ddd',
  '하하배협': 'hyeop_ddd',
  '하하배고': 'go_ddd',
  '하하배중': 'joong_ddd',
  '하하배유': 'yu_ddd',
  '하하배임': 'lim_ddd',
  '하하배이': 'ee_ddd',
  '하하배남': 'nam_ddd',
  '하하배무': 'mu_ddd',
  '하하배응': 'eung_ddd',
  '하배황': 'hwang_dd',
  '하배대': 'dae_dd',
  '하배태': 'tae_dd',
  '하배협': 'hyeop_dd',
  '하배고': 'go_dd',
  '하배중': 'joong_dd',
  '하배유': 'yu_dd',
  '하배임': 'lim_dd',
  '하배이': 'ee_dd',
  '하배남': 'nam_dd',
  '하배무': 'mu_dd',
  '하배응': 'eung_dd',
  '배황': 'hwang_d',
  '배대': 'dae_d',
  '배태': 'tae_d',
  '배협': 'hyeop_d',
  '배고': 'go_d',
  '배중': 'joong_d',
  '배유': 'yu_d',
  '배임': 'lim_d',
  '배이': 'ee_d',
  '배남': 'nam_d',
  '배무': 'mu_d',
  '배응': 'eung_d',
  '황': 'hwang',
  '대': 'dae',
  '태': 'tae',
  '협': 'hyeop',
  '고': 'go',
  '중': 'joong',
  '유': 'yu',
  '임': 'lim',
  '이': 'ee',
  '남': 'nam',
  '무': 'mu',
  '응': 'eung',
  '청황': 'hwang_u',
  '청대': 'dae_u',
  '청태': 'tae_u',
  '청협': 'hyeop_u',
  '청고': 'go_u',
  '청중': 'joong_u',
  '청유': 'yu_u',
  '청임': 'lim_u',
  '청이': 'ee_u',
  '청남': 'nam_u',
  '청무': 'mu_u',
  '청응': 'eung_u',
  '중청황': 'hwang_uu',
  '중청대': 'dae_uu',
  '중청태': 'tae_uu',
  '중청협': 'hyeop_uu',
  '중청고': 'go_uu',
  '중청중': 'joong_uu',
  '중청유': 'yu_uu',
  '중청임': 'lim_uu',
  '중청이': 'ee_uu',
  '중청남': 'nam_uu',
  '중청무': 'mu_uu',
  '중청응': 'eung_uu',
  '-': 'conti',
  '쉼표': 'pause'
}

SYMBOL_W_DUR_LIST = ['노', '니', '로', '리', '니나*', '느나', '노라', '느니', '노라느니', '니레나', '네로나', '니로나', '니느라니', '느나니나', '느나르나니', '같은음표']
SYMBOL_W_DUR_EN_LIST = ['no', 'ni', 'ro', 'ri', 'nina-dur', 'neuna', 'nora', 'neuni', 'noraneuni', 'nirena', 'nerona', 'nirona', 'nineurani', 'neunanina', 'neunareunani', 'repeat']

SYMBOL_WO_DUR_LIST = ['나니나', '나느나', '니레', '니나', '니로', '노네', '너녜', '노니로', '노리노', '네로네', '느네느', '나니로', '느로니르', '느니-르', '니루-니', '나니르노니르', '특강표', '늘임표', '흘림표', '겹흘림표', '반길이표', '덧길이표', '미는표', '떠이어표', '끊는표', '농음표', '풀어내림표']
#'로니로', '격음표'

SYMBOL_WO_DUR_ADD_EN_LIST = ['len-half/len-double', 'len-double/len-half']

SYMBOL_WO_DUR_EN_LIST = ['nanina', 'naneuna', 'nire', 'nina', 'niro', 'none', 'neonye', 'noniro', 'norino', 'nerone', 'neuneneu', 'naniro', 'neuronireu', 'neuni-reu', 'niru-ni', 'nanireunonireu', 'accent', 'fermata', 'flow', 'flow-rep', 'len-half', 'len-double', 'push', 'roll', 'staccato', 'vib', 'vib-long'] + SYMBOL_WO_DUR_ADD_EN_LIST 
# 'roniro', 'strike'

SYMBOL_LIST = SYMBOL_W_DUR_LIST + SYMBOL_WO_DUR_LIST
SYMBOL_EN_LIST = SYMBOL_W_DUR_EN_LIST + SYMBOL_WO_DUR_EN_LIST

SYMBOL_W_DUR_EN_TO_KR = {
  'no': '노',
  'ni': '니',
  'ro': '로',
  'ri': '리',
  'nina-dur': '니나*',
  'neuna': '느나',
  'nora': '노라',
  'neuni': '느니',
  'noraneuni': '노라느니',
  'nirena': '니레나',
  'nerona': '네로나',
  'nirona': '니로나',
  'nineurani': '니느라니',
  'neunanina': '느나니나',
  'neunareunani': '느나르나니',
  'repeat': '같은음표'
}

SYMBOL_W_DUR_KR_TO_EN = {
  '노': 'no',
  '니': 'ni',
  '로': 'ro',
  '리': 'ri',
  '니나*': 'nina-dur',
  '느나': 'neuna',
  '노라': 'nora',
  '느니': 'neuni',
  '노라느니': 'noraneuni',
  '니레나': 'nirena',
  '네로나': 'nerona',
  '니로나': 'nirona',
  '니느라니': 'nineurani',
  '느나니나': 'neunanina',
  '느나르나니': 'neunareunani',
  '같은음표': 'repeat'
}

SYMBOL_WO_DUR_EN_TO_KR = {
  'nanina': '나니나',
  'naneuna': '나느나',
  'nire': '니레',
  'nina': '니나',
  'niro': '니로',
  'none': '노네',
  'neonye': '너녜',
  'noniro': '노니로',
  'norino': '노리노',
  'nerone': '네로네',
  'neuneneu': '느네느',
  'naniro': '나니로',
  # 'roniro': '로니로',
  'neuronireu': '느로니르',
  'neuni-reu': '느니-르',
  'niru-ni': '니루-니',
  'nanireunonireu': '나니르노니르',
  'accent': '특강표',
  'fermata': '늘임표',
  'flow': '흘림표',
  'flow-rep': '겹흘림표',
  'len-half': '반길이표',
  'len-double': '덧길이표',
  'push': '미는표',
  'roll': '떠이어표',
  'staccato': '끊는표',
  'vib': '농음표',
  'vib-long': '풀어내림표',
  'len-half/len-double': '반길이표/덧길이표', 
  'len-double/len-half': '덧길이표/반길이표'
}

SYMBOL_WO_DUR_KR_TO_EN = {
  '나니나': 'nanina',
  '나느나': 'naneuna',
  '니레': 'nire',
  '니나': 'nina',
  '니로': 'niro',
  '노네': 'none',
  '너녜': 'neonye',
  '노니로': 'noniro',
  '노리노': 'norino',
  '네로네': 'nerone',
  '느네느': 'neuneneu',
  '나니로': 'naniro',
  # '로니로': 'roniro',
  '느로니르': 'neuronireu',
  '느니-르': 'neuni-reu',
  '니루-니': 'niru-ni',
  '나니르노니르': 'nanireunonireu',
  '특강표': 'accent',
  '늘임표': 'fermata',
  '흘림표': 'flow',
  '겹흘림표': 'flow-rep',
  '반길이표': 'len-half',
  '덧길이표': 'len-double',
  '미는표': 'push',
  '떠이어표': 'roll',
  '끊는표': 'staccato',
  '농음표': 'vib',
  '풀어내림표': 'vib-long',
  '반길이표/덧길이표': 'len-half/len-double',
  '덧길이표/반길이표': 'len-double/len-half'
}

NAME_EN_TO_KR = dict(PNAME_EN_TO_KR, **SYMBOL_W_DUR_EN_TO_KR, **SYMBOL_WO_DUR_EN_TO_KR)
NAME_KR_TO_EN = dict(PNAME_KR_TO_EN, **SYMBOL_W_DUR_KR_TO_EN, **SYMBOL_WO_DUR_KR_TO_EN)

NOTE_W_DUR_EN_SET = set(PNAME_EN_LIST + SYMBOL_W_DUR_EN_LIST)