project_name: 'jeonggan-omr'
model_name: 'transformer_with_aux_label_240327'
wandb_entity: 'team-halsoo'
wandb_log: true

device: 'cuda:1'

train_set_path: 'data/train/006_all_1711271837.csv'
aux_train_set_path: 'data/low_confident_pairs.csv'

valid_set_path: 'data/valid/006_all_1710296405.csv'
test_set_path: 'data/labels_from_ls_cleaned.csv'

train_batch_size: 100
aux_train_batch_ratio: 0.2

wandb_notes: "log last validation and test result, bottom-30 jeonggan image plot"