general:
  device: cuda:1
  model_name: jeongganbo_omr
  random_seed: 2
  random_seed_synth: 4

wandb:
  project: jeonggan-omr
  entity: <YOUR_WANDB_ENTITY>
  do_log: false
  is_sweep: false

data_path:
  train: data/train/008_4M_1712090605.csv
  train_aux: low_confident_pairs_filtered.csv
  valid_synthed: data/valid/008_4M_1712093199.csv
  valid_HL: data/valid/HL_valid_set_nodups.csv
  test: data/HL_test_set_nodups.csv

test_setting:
  remove_borders: true
  with_best: true
  target_metric: 'exact_all'

dataloader:
  batch_size: 100
  aux_freq: 100
  aux_ratio: 0.01
  mix_aux: false
  num_workers_synth: 8
  num_workers_load: 4

model:
  lr: 1e-3
  dim: 128
  num_heads: 8
  enc_depth: 8
  dec_depth: 4
  dropout: 0.1