general:
  device: cuda:1
  model_name: transformer_with_aux_label

wandb:
  project: my-first-sweep
  entity: team-halsoo
  do_log: false
  is_sweep: false

data_path:
  train: data/debug_train.csv
  train_aux: data/debug_train_aux.csv
  valid_synthed: data/valid/006_all_1710296405.csv
  valid_HL: data/valid/HL_valid_set.csv
  test: data/debug_test.csv

dataloader:
  batch_size: 100
  aux_ratio: 0.2
  num_workers_synth: 8
  num_workers_load: 4
  mix_aux: false

model:
  lr: 1e-3
  dim: 128
  num_heads: 8
  enc_depth: 2
  dec_depth: 6
  dropout: 0.1