entity: team-halsoo
project: my-first-sweep
program: wandb_sweep.py
method: grid
metric:
  goal: maximize
  name: test_acc
parameters:
  model.lr: 
    values: [1e-3, 1e-4]
  model.dim:
    values: [128, 256]
  model.enc_depth:
    values: [4, 6, 8]
  model.dec_depth:
    values: [4, 6, 8]

command:
#  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +wandb.is_sweep=true